# Generated by Django 4.2.5 on 2023-11-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destacado_por_categoria',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='destacado_por_categoria',
            old_name='stock_item',
            new_name='stock_item_id',
        ),
    ]
