# Generated by Django 4.2.5 on 2023-11-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_categoria_destacado_por_categoria_categoria_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destacado_por_categoria',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='destacado_por_categoria',
            old_name='stock_item_id',
            new_name='stock_item',
        ),
    ]
