# Generated by Django 4.2.5 on 2023-11-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_color_alter_stock_item_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500, null=True)),
                ('estrellas', models.IntegerField(choices=[(1, 'Una estrella'), (2, 'Dos estrellas'), (3, 'Tres estrellas'), (4, 'Cuatro estrellas'), (5, 'Cinco estrellas')], null=True)),
                ('emailcontacto', models.EmailField(max_length=254, null=True)),
                ('item_reseniado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.stock_item')),
            ],
        ),
    ]
